
/*
    Promise.reject(reason) 를 사용하면 catch 로 연결된 rejected 상태로 변경됩니다.
      이또한 Promise 객체 리턴
      https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject
*/

{
  //Promise.reject(reason)

  Promise.reject(new Error('유인아가 막내다'))
    .then()
    .catch(err => {
      console.log(err.message);
    })
  
}